# Generated by Django 2.1.4 on 2018-12-06 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor_ip', models.CharField(max_length=40, unique=True, validators=[django.core.validators.validate_ipv46_address])),
                ('is_activated', models.BooleanField(db_index=True, default=True)),
                ('tms_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
