# Generated by Django 2.1.4 on 2018-12-08 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40, validators=[django.core.validators.validate_ipv46_address])),
                ('is_tor', models.BooleanField(default=None)),
                ('is_proxy', models.BooleanField(default=None)),
                ('tms_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
