# Generated by Django 2.1.4 on 2018-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_device', '0002_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='is_proxy',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checker',
            name='is_tor',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
